-- MySQL Script generated by MySQL Workbench
-- Wed Oct 30 21:44:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_libros` ;

-- -----------------------------------------------------
-- Schema bd_libros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_libros` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `bd_libros` ;

-- -----------------------------------------------------
-- Table `genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genero` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `genero` (
  `id_genero` INT NOT NULL,
  `genero` VARCHAR(45) NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `libro` (
  `id_libro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(150) NOT NULL,
  `autor` VARCHAR(150) NOT NULL,
  `anio_publicacion` INT NOT NULL,
  `anio_lectura` INT NOT NULL,
  `puntiacion` INT NOT NULL,
  `fk_genero` INT NOT NULL,
  PRIMARY KEY (`id_libro`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
